# Site settings
title: Machine Learning and Adaptive Intelligence 2015
email: N.Lawrence@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Module on machine learning and Adaptive Intelligence as taught in 2015.
baseurl: "/mlai2015" # the subpath of your site, e.g. /blog/
url: "http://inverseprobability.com/" # the base hostname & protocol for your site
youtube:
- width: 800
- height: 600
gitraw: "https://raw.githubusercontent.com/lawrennd/mlai2015/master"
nbviewer: "http://nbviewer.ipython.org/github/lawrennd/mlai2015/blob/master"
twitter_username: lawrennd
github_username:  lawrennd

# Build settings
markdown: kramdown
