# Site settings
title: Machine Learning and Adaptive Intelligence 2013-14
email: N.Lawrence@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://inverseprobability.com/mlai2014/" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd

# Build settings
markdown: kramdown
